Add DirectComposition sample
microsoft/windows-rs pull request #2129
Opened 2022-10-31 20:28 UTC by kennykerr

This sample illustrates various concepts related to UI development for Windows including:

* DirectComposition
* Direct2D
* DirectWrite
* Windows Animation Manager
* Windows Imaging Component

This sample first appeared in my [DirectComposition course on Pluralsight](https://www.pluralsight.com/courses/directcomposition-in-action). 

![dcomp](https://user-images.githubusercontent.com/9845234/199103049-78e6c647-abfd-438a-8b11-ca1ba3ea7dd8.gif)

2022-10-31 23:29 UTC, riverar requested changes
`image.jpg` appears to be corrupted, leading to panic.

```
code: HRESULT(0x88982F60), message: "The image is unrecognized."
```

2022-10-31 23:29 UTC, riverar commented on crates/samples/dcomp/src/main.rs
> +    }
I'm not sure where you get the debug layers these days; this doesn't work on my retail Windows 11 machines.

```
Error { code: HRESULT(0x887A002D), message: "The application requested an operation that depends on an SDK component that is missing or mismatched."
```

2022-10-31 23:29 UTC, riverar commented on crates/samples/dcomp/src/main.rs
> +            None,
Optional: Consider using `D3D_DRIVER_TYPE_WARP` instead for better perf over RDP.

2022-10-31 23:40 UTC, riverar commented on crates/samples/dcomp/src/main.rs
> +    }
Update: We can add this to the `README.md`:

To run this sample, you will need the Direct3D 11 debug layer installed. To install the layer, go to Settings > Apps > Optional features and add the optional feature `Graphics Tools`.

2022-10-31 23:53 UTC, riverar approved these changes
Tested on aarch64, works well.

2022-11-01 12:40 UTC, merged

2022-11-02 15:23 UTC, kennykerr commented on crates/samples/dcomp/src/main.rs
> +        }
In that case yes, but in general most of the functions make so many unsafe calls it becomes very noisy. Not sure how to think about that.

2022-11-02 19:14 UTC, kennykerr commented on crates/samples/dcomp/src/main.rs
> +        }
Sure, feel free to contribute something like that. I find it highly subjective and would really like to reduce the underlying *need* for `unsafe` in the first place. Many of these calls are perfectly safe. I just need to think some more about how to define that.

2023-02-18 14:22 UTC, Godnoken commented
Thank you for this! I read your article from 2014 about DirectComposition and transparency and tried to implement it myself in Rust before finding out you already had done it yourself.

I just have one question. Is there a simple way in this example to make the transparent areas click-through to the windows behind? Like using `HTTRANSPARENT` on `NCHITTEST`, but instead propagating down to windows that are not on the same thread.

If you have any quick solution or perhaps a link to information for me to dig through, that would be very much appreciated, thank you.

2023-02-19 02:04 UTC, kennykerr commented
2014 was a long time ago. 😜 I don't recall exactly, but I thought `WS_EX_NOREDIRECTIONBITMAP` along with a 0% alpha channel was all it took. @robmikh may know for sure.

2023-02-19 11:29 UTC, Godnoken commented
Haha, indeed! Hmm. But is it possible to set a 0% alpha channel without `WS_EX_LAYERED`, and if not, wouldn't that put me back to square one performance-wise?

2023-02-20 19:20 UTC, kennykerr commented
Dug into this a bit. Unfortunately, if you need per-pixel hit testing then you need a layered window e.g. `WS_EX_LAYERED` with the implied performance penalty. Nothing has changed from what I described in that 2014 article.

2023-02-20 22:31 UTC, Godnoken commented
Ah, that's too bad, but I think I'll be able to come up with a solution that fits my purposes anyways.
Thank you very much!